spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/plants_db
spring.datasource.username=root
spring.datasource.password=eesa@007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
